# Generated by Django 5.2.3 on 2025-06-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('published_date', models.DateField()),
                ('keywords', models.JSONField(default=list)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='researchlens.author')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('source_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_similarities', to='researchlens.paper')),
                ('target_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_similarities', to='researchlens.paper')),
            ],
        ),
    ]
