# Generated by Django 5.2.3 on 2025-06-14 21:44

import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchlens', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
        migrations.RunSQL("ALTER TABLE researchlens_paper ADD COLUMN embedding_new vector(384);"),
        migrations.RunSQL("ALTER TABLE researchlens_paper DROP COLUMN embedding;"),
        migrations.RunSQL("ALTER TABLE researchlens_paper RENAME COLUMN embedding_new TO embedding;"),
        migrations.AddField(
            model_name='paper',
            name='categories',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
