INSERT INTO public.researchlens_author (id, name, institution) VALUES (1, 'Stephen F. Bush', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (2, 'John Hershey', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (3, 'Kirby Vosburgh', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (4, 'Franco Milicchio', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (5, 'Yang Shen', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (6, 'Min Xie', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (7, 'Wenzhe Zhang', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (8, 'Tao Wu', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (9, 'Pratik Mishra', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (10, 'Rekha Pitchumani', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (11, 'Yang Suk Kee', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (12, 'Vladimir V. Kisil', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (13, 'Donald E. Knuth', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (14, 'C. Gordon Bell', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (15, 'Jim Gray', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (16, 'Douglas M. Snyder', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (17, 'Krzysztof R. Apt', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (18, 'Ingo Blechschmidt', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (19, 'Aravind Asok', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (20, 'Graham Manuell', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (21, 'Friedrich Wehrung', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (22, 'Nik Weaver', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (23, 'Morimichi Kawasaki', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (24, 'Mitsuaki Kimura', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (25, 'Hiroki Kodama', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (26, 'Yoshifumi Matsuda', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (27, 'Takahiro Matsushita', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (28, 'Ryuma Orita', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (29, 'Vladimir Dotsenko', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (30, 'Sergey Shadrin', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (31, 'Bruno Vallette', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (32, 'Domenico Fiorenza', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (33, 'Niels Kowalzig', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (34, 'Maxim Kontsevich', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (35, 'Yan Soibelman', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (36, 'Angelo Mazza', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (37, 'Antonio Punzo', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (38, 'Brian McGuire', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (39, 'Mohammad Fayaz', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (40, 'Alireza Abadi', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (41, 'Soheila Khodakarim', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (42, 'Sanket Jantre', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (43, 'Ivano Azzini', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (44, 'Domenico Perrotta', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (45, 'Francesca Torti', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (46, 'Kevin C. Lutz', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (47, 'Michael L. Neugent', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (48, 'Tejasv Bedi', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (49, 'Nicole J. De Nisco', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (50, 'Qiwei Li', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (51, 'Li Tuobang', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (52, 'Aneel Bhusal', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (53, 'Todd D. Little', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (54, 'Florian Ziel', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (55, 'Paul A. Roediger', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (56, 'Jose Mauricio Gomez Julian', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (57, 'Amir Ban', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (58, 'Moran Koren', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (59, 'Victor Chernozhukov', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (60, 'Alfred Galichon', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (61, 'Marc Henry', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (62, 'Brendan Pass', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (63, 'Rahul Deb', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (64, 'Yuichi Kitamura', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (65, 'John K. -H. Quah', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (66, 'Jörg Stoye', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (67, 'Patrick H. O''Callaghan', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (68, 'Paul Heidhues', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (69, 'Philipp Strack', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (70, 'Qingyin Ma', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (71, 'John Stachurski', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (72, 'Alexis Akira Toda', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (73, 'Victor H. Aguiar', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (74, 'Per Hjertstrand', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (75, 'Roberto Serrano', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (76, 'Drew Fudenberg', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (77, 'Whitney K. Newey', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (78, 'Tomasz Strzalecki', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (79, 'Kfir Eliaz', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (80, 'Ran Spiegler', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (81, 'Yair Weiss', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (82, 'Enrique M. Padilla', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (83, 'Birgit L. Emberger', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (84, 'Manuel Diez-Minguito', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (85, 'Steven N. Shore', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (86, 'Václav Pavlík', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (87, 'Osame Kinouchi', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (88, 'Angélica A. Mandrá', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (89, 'İzzet Sakallı', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (90, 'C. J. Efthimiou', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (91, 'R. A. Llewellyn', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (92, 'Aleksey A. Zakharenko', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (93, 'S. Karthikyan', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (94, 'K. S. Kim', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (95, 'Garima Malhotra', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (96, 'Timothy Fuller-Rowell', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (97, 'Tzu-Wei Fang', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (98, 'Valery Yudin', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (99, 'Svetlana Karol', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (100, 'Erich Becker', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (101, 'Adam Marshall Kubaryk', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (102, 'Yongfeng Yang', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (103, 'J. J. Blackstock', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (104, 'D. S. Battisti', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (105, 'K. Caldeira', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (106, 'D. M. Eardley', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (107, 'J. I. Katz', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (108, 'D. W. Keith', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (109, 'A. A. N. Patrinos', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (110, 'D. P. Schrag', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (111, 'R. H. Socolow', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (112, 'S. E. Koonin', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (113, 'Dimitar Ouzounov', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (114, 'Sergey Pulinets', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (115, 'Dmitry Davidenko', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (116, 'Karsten Kruse', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (117, 'Rémi Berthoz', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (118, 'Luca Barberi', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (119, 'Anne-Cécile Reymann', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (120, 'Daniel Riveline', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (121, 'Ali Navid', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (122, 'Eivind Almaas', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (123, 'Fabian V. Filipp', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (124, 'Evangelos-Marios Nikolados', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (125, 'Andrea Y. Weiße', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (126, 'Diego A. Oyarzún', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (127, 'Günther Knör', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (128, 'Mark Catherall', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (129, 'Leonid A. Mirny', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (130, 'Zeba Wunderlich', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (131, 'Christian Thiede', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (132, 'Gerhard Ehninger', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (133, 'Kai Simons', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (134, 'Michal Grzybek', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (135, 'Adam Stefanko', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (136, 'Nikolai Slavov', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (137, 'Sefan Semrau', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (138, 'Edoardo Airoldi', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (139, 'Bogdan Budnik', null);
INSERT INTO public.researchlens_author (id, name, institution) VALUES (140, 'Alexander van Oudenaarden', null);
